services:
  - type: web
    name: koersen-app
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
